# Aufgabe 12.1 & 12.2
E!rfordert kein Einsatz von Python.

# Aufgabe 12.3

Es wird angenommen, dass vier Faktoren den Geschmack eines Erfrischungsgetränks beeinﬂussen:  
A) die Art des Süssungsmittels  
B) das Verhältnis von Sirup zu Wasser   
C) Kohlensäuregehalt  
D) und Temperatur  
Jeder Faktor kann auf zwei Ebenen ausgeführt werden, was ein 24 Design ergibt. Bei jedem Durchlauf des Designs werden Proben des Getränks an eine Testgruppe Testpanel, bestehend aus 20 Personen, gegeben. Jeder Tester ordnet dem Getränk eine Punktzahl von 1 bis 10. Die Gesamtpunktzahl ist die Reaktionsvariable, und das Ziel ist es, eine Rezeptur zu ﬁnden, die die Gesamtpunktzahl maximiert. Es werden zwei Wiederholungen dieses Designs durchgeführt, und die Ergebnisse sind in der Tabelle dargestellt.

In [3]:
import numpy as np
import pandas as pd
from statsmodels.formula.api import ols
from patsy.contrasts import Treatment, Sum 
from statsmodels.stats.anova import anova_lm

df = pd.DataFrame({'Aa': np.tile(np.tile([-1, 1], 8),2), 
'Bb': np.tile(np.repeat([-1,1], [2,2]),8),
'Cc': np.tile(np.repeat([-1,1], [4,4]),4), 
'Dd': np.tile(np.repeat([-1,1], [8,8]),2)},
dtype='category')

df['Yy']=np.array([159,168,158,166,175,179,173,179,164,187,163,185,168,197,170,194,163,
175,163,168,178,183,168,182,159,189,159,191, 174, 199,174,198])

print(df)

   Aa Bb Cc Dd   Yy
0  -1 -1 -1 -1  159
1   1 -1 -1 -1  168
2  -1  1 -1 -1  158
3   1  1 -1 -1  166
4  -1 -1  1 -1  175
5   1 -1  1 -1  179
6  -1  1  1 -1  173
7   1  1  1 -1  179
8  -1 -1 -1  1  164
9   1 -1 -1  1  187
10 -1  1 -1  1  163
11  1  1 -1  1  185
12 -1 -1  1  1  168
13  1 -1  1  1  197
14 -1  1  1  1  170
15  1  1  1  1  194
16 -1 -1 -1 -1  163
17  1 -1 -1 -1  175
18 -1  1 -1 -1  163
19  1  1 -1 -1  168
20 -1 -1  1 -1  178
21  1 -1  1 -1  183
22 -1  1  1 -1  168
23  1  1  1 -1  182
24 -1 -1 -1  1  159
25  1 -1 -1  1  189
26 -1  1 -1  1  159
27  1  1 -1  1  191
28 -1 -1  1  1  174
29  1 -1  1  1  199
30 -1  1  1  1  174
31  1  1  1  1  198

a) Gibt es Variablen, die nicht relevant für die Gesamtpunktezahl ist (ohne Interaktion)?

In [6]:
fit = ols("Yy ~ C(Aa, Sum)+C(Bb, Sum)+C(Cc, Sum)+C(Dd, Sum)", data=df).fit()
anova_lm(fit)

              df    sum_sq      mean_sq          F        PR(>F)
C(Aa, Sum)   1.0  2312.000  2312.000000  71.290792  4.687651e-09
C(Bb, Sum)   1.0    21.125    21.125000   0.651392  4.266685e-01
C(Cc, Sum)   1.0   946.125   946.125000  29.173876  1.038119e-05
C(Dd, Sum)   1.0   561.125   561.125000  17.302355  2.897778e-04
Residual    27.0   875.625    32.430556        NaN           NaN

Die Variable B (Verhältnis Sirup Wasser) ist die einzige Variable, die nicht hochsigniﬁkant ist.

b) Gibt es statistisch signiﬁkante Interaktion? Können Sie diese begründen?  
Verwenden Sie α = 0.05 in den statistischen Tests.

In [7]:
fit = ols("Yy ~ C(Aa, Sum)*C(Bb, Sum)*C(Cc, Sum)*C(Dd, Sum)", data=df).fit()
anova_lm(fit)

,df,sum_sq,mean_sq,F,PR(>F)
"C(Aa, Sum)",1.0,2.312000e+03,2.312000e+03,2.417778e+02,4.450669e-11
"C(Bb, Sum)",1.0,2.112500e+01,2.112500e+01,2.209150e+00,1.566329e-01
"C(Cc, Sum)",1.0,9.461250e+02,9.461250e+02,9.894118e+01,2.957845e-08
"C(Dd, Sum)",1.0,5.611250e+02,5.611250e+02,5.867974e+01,9.692188e-07
"C(Aa, Sum):C(Bb, Sum)",1.0,1.250000e-01,1.250000e-01,1.307190e-02,9.103968e-01
"C(Aa, Sum):C(Cc, Sum)",1.0,3.125000e+00,3.125000e+00,3.267974e-01,5.754947e-01
"C(Bb, Sum):C(Cc, Sum)",1.0,5.000000e-01,5.000000e-01,5.228758e-02,8.220265e-01
"C(Aa, Sum):C(Dd, Sum)",1.0,6.661250e+02,6.661250e+02,6.966013e+01,3.186635e-07
"C(Bb, Sum):C(Dd, Sum)",1.0,1.250000e+01,1.250000e+01,1.307190e+00,2.697232e-01
"C(Cc, Sum):C(Dd, Sum)",1.0,1.250000e+01,1.250000e+01,1.307190e+00,2.697232e-01
"C(Aa, Sum):C(Bb, Sum):C(Cc, Sum)",1.0,4.500000e+00,4.500000e+00,4.705882e-01,5.025369e-01
"C(Aa, Sum):C(Bb, Sum):C(Dd, Sum)",1.0,2.000000e+00,2.000000e+00,2.091503e-01,6.535827e-01
"C(Aa, Sum):C(Cc, Sum):C(Dd, Sum)",1.0,1.774937e-26,1.774937e-26,1.856143e-27,1.000000e+00
"C(Bb, Sum):C(Cc, Sum):C(Dd, Sum)",1.0,1.250000e-01,1.250000e-01,1.307190e-02,9.103968e-01
"C(Aa, Sum):C(Bb, Sum):C(Cc, Sum):C(Dd, Sum)",1.0,2.112500e+01,2.112500e+01,2.209150e+00,1.566329e-01
Residual,16.0,1.530000e+02,9.562500e+00,NaN,NaN

Die Variabeln A, C (und D?! --> gem. Lösung nicht!) weisen eine Signifikante Interaktion auf.

# Aufgabe 12.4

Siehe Kapitel 13 --> identische Aufgabe