# SW 12

In [1]:
import numpy as np
import pandas as pd
from statsmodels.formula.api import ols
from patsy.contrasts import Treatment, Sum 
from statsmodels.stats.anova import anova_lm

df = pd.DataFrame({
'Aa': np.tile(np.tile([-1, 1], 4),2),
'Bb': np.tile(np.repeat([-1,1], [2,2]),4), 
'Cc': np.tile(np.repeat([-1,1], [4,4]),2)}, 
dtype='category')

df['Yy'] = np.array([34,26,33,21,24,23,19,18,34,26,33,21,24,23,19,18])

fit = ols('Yy ~ C(Aa, Sum)*C(Bb, Sum)*C(Cc, Sum)', data=df).fit()

fit.params

Intercept                                             24.75
C(Aa, Sum)[S.-1]                                       2.75
C(Bb, Sum)[S.-1]                                       2.00
C(Cc, Sum)[S.-1]                                       3.75
C(Aa, Sum)[S.-1]:C(Bb, Sum)[S.-1]                     -0.50
C(Aa, Sum)[S.-1]:C(Cc, Sum)[S.-1]                      2.25
C(Bb, Sum)[S.-1]:C(Cc, Sum)[S.-1]                     -0.50
C(Aa, Sum)[S.-1]:C(Bb, Sum)[S.-1]:C(Cc, Sum)[S.-1]    -0.50
dtype: float64

In [6]:
import numpy as np

df['Yy'] = np.array([34,26,33,21,24,23,19,18,40,29,35,22,23,22,18,18])

fit = ols('Yy ~ C(Aa, Sum)*C(Bb, Sum)*C(Cc, Sum)', data=df).fit()

anova_lm(fit)

,df,sum_sq,mean_sq,F,PR(>F)
"C(Aa, Sum)",1.0,138.0625,138.0625,41.679245,0.000197
"C(Bb, Sum)",1.0,85.5625,85.5625,25.830189,0.000950
"C(Cc, Sum)",1.0,351.5625,351.5625,106.132075,0.000007
"C(Aa, Sum):C(Bb, Sum)",1.0,1.5625,1.5625,0.471698,0.511620
"C(Aa, Sum):C(Cc, Sum)",1.0,105.0625,105.0625,31.716981,0.000492
"C(Bb, Sum):C(Cc, Sum)",1.0,0.0625,0.0625,0.018868,0.894140
"C(Aa, Sum):C(Bb, Sum):C(Cc, Sum)",1.0,3.0625,3.0625,0.924528,0.364446
Residual,8.0,26.5000,3.3125,NaN,NaN

In [7]:
anti = pd.DataFrame({
	'Anzahl': np.tile([-1, 1], 8),
	'VolPrs': np.tile(np.repeat([-1, 1], [2, 2]), 4),
	'Zeit': np.tile(np.repeat([-1, 1], [4, 4]), 2),
	'RadDos': np.repeat([-1, 1], [8, 8]),
	'Entw': [-1, 1, 1, -1, 1, -1, -1, 1, -1, 1, 1, -1, 1, -1, -1, 1],
	'Inj2': [-1, -1, 1, 1, 1, 1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1]
}, dtype='category')

anti['Yy'] = np.array([70, 150, 34, 32, 137.5, 56, 123, 225, 50, 2.7, 1.2, 12, 90, 2.1, 4, 15])

fit = ols('Yy ~ C(Anzahl, Sum) + C(VolPrs, Sum) + C(Zeit, Sum) + C(RadDos, Sum) + C(Entw, Sum) + C(Inj2, Sum)', data=anti).fit()
anova_lm(fit)

                 df        sum_sq       mean_sq          F    PR(>F)
C(Anzahl, Sum)  1.0     13.875625     13.875625   0.006492  0.937543
C(VolPrs, Sum)  1.0    785.400625    785.400625   0.367488  0.559354
C(Zeit, Sum)    1.0   5651.280625   5651.280625   2.644229  0.138371
C(RadDos, Sum)  1.0  26446.890625  26446.890625  12.374474  0.006539
C(Entw, Sum)    1.0   5863.730625   5863.730625   2.743634  0.132024
C(Inj2, Sum)    1.0   7314.525625   7314.525625   3.422459  0.097353
Residual        9.0  19234.920625   2137.213403        NaN       NaN

In [12]:
fit = ols('Yy ~ C(Anzahl, Sum) + C(VolPrs, Sum) + C(Zeit, Sum) + C(RadDos, Sum) + C(Entw, Sum) + C(Inj2, Sum)', data=anti).fit()
fit.params

Intercept               62.78125
C(Anzahl, Sum)[S.-1]     0.93125
C(VolPrs, Sum)[S.-1]     7.00625
C(Zeit, Sum)[S.-1]     -18.79375
C(RadDos, Sum)[S.-1]    40.65625
C(Entw, Sum)[S.-1]     -19.14375
C(Inj2, Sum)[S.-1]      21.38125
dtype: float64